version: '3.7'

services: 
  api: 
    build: 
      context: .
    volumes: 
      - static_data:/vol/web
    environment: 
      - SECRET_KEY=lor11022020!
      - ALLOWED_HOST=192.168.7.94

  proxy: 
    build: 
      context: ./proxy
    volumes: 
      - static_data:/vol/static
    ports: 
      - "8080:8080"
    depends_on: 
      - api

volumes: 
  static_data: 
