# Generated by Django 3.1.4 on 2021-04-16 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210401_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_request',
            field=models.DateTimeField(default=datetime.date(2021, 4, 15), null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
