# Generated by Django 3.1.4 on 2021-05-09 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210416_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_request',
            field=models.DateTimeField(default=datetime.date(2021, 5, 8), null=True),
        ),
    ]
