# Generated by Django 3.1.4 on 2021-05-10 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210509_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='score',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_request',
            field=models.DateTimeField(default=datetime.date(2021, 5, 9), null=True),
        ),
    ]
