# Generated by Django 3.1.4 on 2021-05-25 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210511_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_request',
            field=models.DateTimeField(default=datetime.date(2021, 5, 24), null=True),
        ),
    ]
