# Generated by Django 3.1.4 on 2021-06-15 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210613_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_request',
            field=models.DateTimeField(default=datetime.date(2021, 6, 14), null=True),
        ),
    ]
