# Generated by Django 3.1.4 on 2021-07-04 04:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210615_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 4, 40, 56, 747865, tzinfo=utc), null=True),
        ),
    ]
