# Generated by Django 3.1.4 on 2021-03-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210302_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(max_length=200)),
                ('exp_month', models.CharField(max_length=5)),
                ('exp_year', models.CharField(max_length=5)),
                ('cvc', models.CharField(max_length=5)),
                ('amount', models.CharField(default='0', max_length=5)),
            ],
        ),
    ]
