# Generated by Django 3.1.4 on 2021-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='email',
            field=models.CharField(default='email address', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='sub_plan',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
