# Generated by Django 3.1.4 on 2021-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210315_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='email',
            field=models.CharField(max_length=50, verbose_name='email ads'),
        ),
    ]
