# Generated by Django 3.1.4 on 2021-03-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210315_1941'),
        ('accounts', '0014_customuser_last_request'),
    ]

    operations = [
    ]
