# Generated by Django 3.1.4 on 2021-03-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210317_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_request',
            field=models.DateTimeField(default='00-00-00', null=True),
        ),
    ]
