# Generated by Django 3.1.4 on 2021-03-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210317_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_request',
            field=models.DateTimeField(default='2020-01-01 06:00:00.000000-08:00', null=True),
        ),
    ]
