# Generated by Django 3.1.4 on 2021-06-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0011_coin_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtoapprove',
            name='scene_id',
            field=models.IntegerField(default=0),
        ),
    ]
