# Generated by Django 3.1.4 on 2021-06-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0013_purchased_scene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_scene',
            name='scene_name',
        ),
        migrations.AddField(
            model_name='purchased_scene',
            name='scene_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
