# Generated by Django 3.1.4 on 2021-07-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0016_auto_20210615_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtoapprove',
            name='scored_scene',
            field=models.BooleanField(default=False),
        ),
    ]
